### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by memin-01** [Ariorh1337/flyff_bot#9]
Hi, I don't see the cheat window anymore.

**Comment by you3h** [comment]
@Ariorh1337 are you still working on this proejct? I can try to fix the current issue where in the script injection is not possible anymore. I'll create a PR when you are still here to approve

**Comment by you3h** [comment]
Ah my plan is to also look into it this coming weekend, If you say that you got it on weekend then I will not try to fix it.

@memin-01 This may help but to make it work now, I am running the flyff.js manually via the console of my flyff universe tab. So in order to do this you can get the flyff.js from the zip file provided here.

**Comment by memin-01** [comment]
> Ah, mi plan es revisarlo también este próximo fin de semana. Si dices que lo conseguiste el fin de semana, entonces no intentaré arreglarlo.
> 
> @memin-01Esto puede ayudar, pero para que funcione ahora, estoy ejecutando flyff.js manualmente a través de la consola de mi pestaña del universo flyff. Para hacer esto, puede obtener flyff.js del archivo zip que se proporciona aquí.

I thank you very much, Version 0.1.2 is working excellent.
